@startuml
skinparam classAttributeIconSize 0
class 空車リスト  {
+希望日空車一覧():String
+当日空車一覧():String
}
class 車 {
- 車種:String
- 型番号:String
- 号車:String
}
class 顧客 {
- 予約者:void
- 借用者:String
}
class 予約 {
- 予約番号:int
}
class 貸出{
+ 貸出():void
}
@enduml