@startuml 
 hide footbox
skinparam style strictuml /' 厳密なUMLに準拠する'/
participant "利用者:入力画面" as gest
participant ":予約画面" as ReservationScreen

activate gest
gest ->> ReservationScreen: ログイン情報入力（）

activate ReservationScreen
    ReservationScreen -> ReservationScreen: 確認操作（）
    activate ReservationScreen
deactivate ReservationScreen

@enduml