@startuml ステートマシン図
left to right direction
skinparam monochrome true

[*] --> 料金投入待ち : 初期状態

料金投入待ち --> ボタン選択待ち : お金を入れる
ボタン選択待ち --> ドリンク排出中 : ボタンを押す
ドリンク排出中 --> 料金投入待ち : ドリンクの排出完了

料金投入待ち --> [*] : ドリンクの受け取り完了

@endum