@startuml
state メニュー
state 今の順番
state 予約と確認
state あなたの順番

[*] --> メニュー
メニュー --> 予約と確認 : 予約
予約と確認 --> メニュー : 取消ボタンを押す
予約と確認 --> あなたの順番 : 登録する
予約と確認 --> あなたの順番 : 確認する
メニュー <-- あなたの順番 : メニューボタンを押す
メニュー --> 今の順番 : 今の順番ボタンを押す
メニュー <-- 今の順番 : メニューボタンを押す
メニュー --> [*]
@enduml
