@startuml
left to right direction

actor 客 #DDDDDD
actor ベンダー #DDDDDD

rectangle 自動販売機 {
    usecase "飲み物選択" as 選択
    usecase "支払い" as 支払い
    usecase "飲み物提供" as 提供
}

客 -- 選択
客 -- 支払い
提供 -- ベンダー
@enduml

